# Generated by Django 4.0.2 on 2023-02-01 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_booktable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter numbers upto 10-digits allowed', regex='^\\d{10}$')]),
        ),
    ]
