# Generated by Django 4.0.2 on 2023-02-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id', models.UUIDField(default='095EF', editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
