# Generated by Django 4.0.2 on 2023-02-10 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_menu_id_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb6f00b4-d6cb-461e-99f9-5156a818dcce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
