# Generated by Django 4.0.2 on 2023-02-10 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd0ec85d-4ae7-4bb9-bb47-bef96dcac3f1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
