# Generated by Django 4.0.2 on 2023-02-10 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fa11b16-3d64-4013-b898-013f18e63b41'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
