# Generated by Django 4.0.2 on 2023-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
