# Generated by Django 4.2.4 on 2023-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_cart_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
