# Generated by Django 4.2.4 on 2023-08-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_menu_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="item_id",
            new_name="menu_item",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="item_name",
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="MenuImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="menu_item_img/")),
                (
                    "menu_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.menu"
                    ),
                ),
            ],
        ),
    ]
