# Generated by Django 4.2.4 on 2023-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0018_rename_item_id_cart_menu_item_remove_cart_item_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menuimg",
            name="menu_name",
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
