# Generated by Django 4.2.4 on 2023-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_menuimg_menu_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuimg",
            name="menu_name",
        ),
        migrations.AddField(
            model_name="menuimg",
            name="name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
