# Generated by Django 4.2.4 on 2023-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_remove_menuimg_menu_name_menuimg_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuimg",
            name="img",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
