# Generated by Django 4.2.4 on 2023-08-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_cart_price_alter_menuimg_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
