# Generated by Django 4.2.4 on 2023-08-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_alter_cart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
